name: CI
on:
  pull_request:
    branches: [pre-main, main]
jobs:
  quality:
    uses: leaflockio/core-actions/.github/workflows/tpl-common-ci.yml@v1
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
  node:
    uses: leaflockio/core-actions/.github/workflows/tpl-node-ci.yml@v1
  branch-policy:
    uses: leaflockio/core-actions/.github/workflows/tpl-branch-policy.yml@v1
