name: Pre-release
on:
  push:
    branches: [pre-main]
jobs:
  release:
    uses: leaflockio/core-actions/.github/workflows/tpl-release.yml@v1
    secrets:
      APP_ID: ${{ secrets.LOCKET_CI_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.LOCKET_CI_PRIVATE_KEY }}

  deploy-qa:
    needs: release
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v4
        with: { ref: pre-main, fetch-depth: 0 }
      - run: git pull origin pre-main
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: npm ci
      - name: Build
        run: npm run build -- --mode qa
        env:
          FP_FIRST_NAME: ${{ secrets.FP_FIRST_NAME }}
          FP_LAST_NAME: ${{ secrets.FP_LAST_NAME }}
          FP_PROFILE_PATH: ${{ secrets.FP_PROFILE_PATH }}
          FP_EMAIL: ${{ secrets.FP_EMAIL }}
          FP_PHONE_COUNTRY_CODE: ${{ secrets.FP_PHONE_COUNTRY_CODE }}
          FP_PHONE_NUMBER: ${{ secrets.FP_PHONE_NUMBER }}
          FP_SHOW_CONTACT_ON_ERROR: ${{ secrets.FP_SHOW_CONTACT_ON_ERROR }}
      - uses: leaflockio/core-actions/actions/deploy/netlify@v1
        with:
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site-id: ${{ secrets.NETLIFY_QA_SITE_ID }}
          environment: QA
